version: 2

sources:
  name: raw_source
  database: airflow
  schema: raw
  tables:
    name: raw_batch_data

  name: staging_source
  database: airflow
  schema: staging
  tables:
    name: dim_address
    name: dim_data
    name: dim_finance
    name: fact_network_usage

  name: trusted_source
  database: airflow
  schema: trusted
  tables:
    name: payment_data
    name: technical_data
    name: non_pii_data
    name: pii_data
    